---
- hosts: all
  become: true
  tasks:
          - name: Zabbix agent stop
            service:
                    name: zabbix-agent
                    state: stopped
          
          - name: Delete zabbix agent on RH family
            yum:
                    name=zabbix-agent
                    state=absent
            when:
                    ansible_os_family == "RedHat"


          - name: Delete zabbix-agent on Debian family
            apt:
                    name: zabbix-agent
                    state: absent
            when:
                    ansible_os_family == "Debian"

          - name: Delete files on Debian families
            file:
                    path='/etc/zabbix/'
                    state=absent
            when:
                    ansible_os_family == "Debian"

          - name: Delete files on RH families
            file:
                    path='/etc/zabbix_agentd.conf'
                    state=absent
            when:
                    ansible_os_family == "RedHat"
